### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by brian-rose** [conda-forge/climlab-feedstock#1]
Getting a working Windows build is a priority. `climlab` is, among other things, educational software designed for classroom use on students' laptops. 

The catch is that `climlab` contains Fortran extensions that are wrapped with `f2py`. Is it currently possible to build with `f2py` for Windows on conda-forge? I have not been able to find any examples of this. From what I can gather, it may not be possible until there is a working Windows condo-forge recipe for numpy itself, e.g. this discussion:
https://github.com/conda-forge/numpy-feedstock/issues/46

Anyone have thoughts or suggestions?

**Comment by ocefpaf** [comment]
I have limited success using `Fortran` with Python 2.7. See https://github.com/conda-forge/pyspharm-feedstock

**Comment by brian-rose** [comment]
Oh, awesome! That is the only Fortran build recipe I've seen for Windows. I will try to the same recipe for climlab and see what happens. Thanks.

**Comment by brian-rose** [comment]
As of PR #2, we now have a working build for Win-32.

**Comment by brian-rose** [comment]
And with PR #3 we have working builds for win64 too!

**Comment by brian-rose** [comment]
Closing.
